version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/helloworld

permissions:
  - object: /home/ubuntu/manage.py
    owner: ubuntu
    mode: 644
    type:
      - file

hooks:
  BeforeInstall:
      - location: scripts/before_install.sh
  AfterInstall:
      - location: scripts/after_install.sh
        
